# -*- coding: utf-8 -*-
"""final work-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VtVgqLi0ugUaASOdJYtJOnfT7k7PjR9I
"""

import requests
from bs4 import BeautifulSoup


url = 'https://www.data.jma.go.jp/obd/stats/etrn/view/daily_s1.php?prec_no=44&block_no=47662&year=2022&month=12&day=&view=a2'

response = requests.get(url)
html = response.text


soup = BeautifulSoup(html, 'html.parser')

humidity_table = soup.find('table', {'class': 'data2_s'})

scraped_data = []
if humidity_table:
    rows = humidity_table.find_all('tr')


    for row in rows[16:]:
        columns = row.find_all('td')


        if len(columns) >= 8:

            day = columns[0].text.strip()
            avg_humidity = columns[16].text.strip()

            scraped_data.append({
                '日': f'{day}',
                '湿度': int(avg_humidity)
            })

            print(f'日:{day} 平均湿度: {avg_humidity}')
        else:
            print('列の数が足りません。')
else:
    print('平均湿度のデータが見つかりませんでした。')

import pandas as pd
df=pd.read_csv('local-data.csv')

day_column = df['日']
avg_humidity_column = df['湿度']

result_df = pd.concat([df['日'], df['湿度']], axis=1)
print(result_df)

import matplotlib.pyplot as plt
if scraped_data:
    scraped_df = pd.DataFrame(scraped_data)
    csv_df = pd.read_csv('local-data.csv', parse_dates=['日'])

plt.figure(figsize=(10, 6))

if '日' in scraped_df.columns:
        plt.plot(scraped_df['日'], scraped_df['湿度'], label='scrapeddata', marker='o')


    if '日' in csv_df.columns:
        plt.plot(csv_df['日'], csv_df['湿度'], label='CSVdata', marker='o')

    plt.title('Humidity data comparison')
    plt.xlabel('day')
    plt.ylabel('humidity')
    plt.legend()
    plt.grid(True)
    plt.show()